# Thalloo Starter Template
#
# This project uses Jekyll to integrate with GitHub Pages.
# Configure the basic settings below to configure your copy.

# Your site settings
title: Agroforestry 
description: > # this means to ignore newlines until "baseurl:"
  A map of the evidence base of agroforestry types -- GIVE BETTER NAME
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://borgstein.github.io/" # the base hostname & protocol for your site
ownername: "Matt"
ownerurl: ""

# Internal configuration
plugins:
  - jekyll-remote-theme
remote_theme: AndrewIOM/thalloo
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
        layout: "default"